
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract profile from tag
      id: extract_profile
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        PROFILE=${TAG_NAME%%-*}
        echo "TAG_NAME=$TAG_NAME"
        echo "PROFILE=$PROFILE"
        echo "profile=$PROFILE" >> $GITHUB_OUTPUT

    - name: Set up Java 24
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '24'

    - name: Build WAR with profile
      run: |
        ./mvnw clean install -Dspring-boot.run.profiles=${{ steps.extract_profile.outputs.profile }} -DskipTests

    - name: Upload WAR to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: target/*.war
        target: /opt/tomcat/webapps/
