name: Deploy WAR to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 24
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '24'

    - name: Build WAR
      run: ./mvnw clean package -DskipTests

    - name: Upload WAR to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: target/*.war
        target: /opt/tomcat/webapps/
