/*
 * Created on 2018-04-14 ( Time 21:52:32 )
 * Generator tool : Telosys Tools Generator ( version 3.0.0 )
 * Copyright 2018 Geo. All Rights Reserved.
 */

package com.wdyapplications.pharmapp.utils.enums;

/**
 * 
 * @author Geo
 *
 */
 public enum FunctionalityEnum {
 	DEFAULT("DEFAULT"),

	// ADRESSE
	VIEW_ADRESSE("VIEW_ADRESSE"),	
	CREATE_ADRESSE("CREATE_ADRESSE"),
	UPDATE_ADRESSE("UPDATE_ADRESSE"),
	DELETE_ADRESSE("DELETE_ADRESSE"),
	// ASSURANCES
	VIEW_ASSURANCES("VIEW_ASSURANCES"),	
	CREATE_ASSURANCES("CREATE_ASSURANCES"),
	UPDATE_ASSURANCES("UPDATE_ASSURANCES"),
	DELETE_ASSURANCES("DELETE_ASSURANCES"),
	// COMMANDE
	VIEW_COMMANDE("VIEW_COMMANDE"),	
	CREATE_COMMANDE("CREATE_COMMANDE"),
	UPDATE_COMMANDE("UPDATE_COMMANDE"),
	DELETE_COMMANDE("DELETE_COMMANDE"),
	// MEDICAMENT
	VIEW_MEDICAMENT("VIEW_MEDICAMENT"),	
	CREATE_MEDICAMENT("CREATE_MEDICAMENT"),
	UPDATE_MEDICAMENT("UPDATE_MEDICAMENT"),
	DELETE_MEDICAMENT("DELETE_MEDICAMENT"),
	// ORDONNANCE
	VIEW_ORDONNANCE("VIEW_ORDONNANCE"),	
	CREATE_ORDONNANCE("CREATE_ORDONNANCE"),
	UPDATE_ORDONNANCE("UPDATE_ORDONNANCE"),
	DELETE_ORDONNANCE("DELETE_ORDONNANCE"),
	// ORDONNANCE_MEDICAMENT
	VIEW_ORDONNANCE_MEDICAMENT("VIEW_ORDONNANCE_MEDICAMENT"),	
	CREATE_ORDONNANCE_MEDICAMENT("CREATE_ORDONNANCE_MEDICAMENT"),
	UPDATE_ORDONNANCE_MEDICAMENT("UPDATE_ORDONNANCE_MEDICAMENT"),
	DELETE_ORDONNANCE_MEDICAMENT("DELETE_ORDONNANCE_MEDICAMENT"),
	// OTP
	VIEW_OTP("VIEW_OTP"),	
	CREATE_OTP("CREATE_OTP"),
	UPDATE_OTP("UPDATE_OTP"),
	DELETE_OTP("DELETE_OTP"),
	// PHARMACIE
	VIEW_PHARMACIE("VIEW_PHARMACIE"),	
	CREATE_PHARMACIE("CREATE_PHARMACIE"),
	UPDATE_PHARMACIE("UPDATE_PHARMACIE"),
	DELETE_PHARMACIE("DELETE_PHARMACIE"),
	// PRIX_MEDICAMENT
	VIEW_PRIX_MEDICAMENT("VIEW_PRIX_MEDICAMENT"),	
	CREATE_PRIX_MEDICAMENT("CREATE_PRIX_MEDICAMENT"),
	UPDATE_PRIX_MEDICAMENT("UPDATE_PRIX_MEDICAMENT"),
	DELETE_PRIX_MEDICAMENT("DELETE_PRIX_MEDICAMENT"),
	// ROLES
	VIEW_ROLES("VIEW_ROLES"),	
	CREATE_ROLES("CREATE_ROLES"),
	UPDATE_ROLES("UPDATE_ROLES"),
	DELETE_ROLES("DELETE_ROLES"),
	// SETTING
	VIEW_SETTING("VIEW_SETTING"),	
	CREATE_SETTING("CREATE_SETTING"),
	UPDATE_SETTING("UPDATE_SETTING"),
	DELETE_SETTING("DELETE_SETTING"),
	// USER_ACTIVITY
	VIEW_USER_ACTIVITY("VIEW_USER_ACTIVITY"),	
	CREATE_USER_ACTIVITY("CREATE_USER_ACTIVITY"),
	UPDATE_USER_ACTIVITY("UPDATE_USER_ACTIVITY"),
	DELETE_USER_ACTIVITY("DELETE_USER_ACTIVITY"),
	// USER_PREFERENCES
	VIEW_USER_PREFERENCES("VIEW_USER_PREFERENCES"),	
	CREATE_USER_PREFERENCES("CREATE_USER_PREFERENCES"),
	UPDATE_USER_PREFERENCES("UPDATE_USER_PREFERENCES"),
	DELETE_USER_PREFERENCES("DELETE_USER_PREFERENCES"),
	// USER_PROFILE
	VIEW_USER_PROFILE("VIEW_USER_PROFILE"),	
	CREATE_USER_PROFILE("CREATE_USER_PROFILE"),
	UPDATE_USER_PROFILE("UPDATE_USER_PROFILE"),
	DELETE_USER_PROFILE("DELETE_USER_PROFILE"),
	// USER_ROLES
	VIEW_USER_ROLES("VIEW_USER_ROLES"),	
	CREATE_USER_ROLES("CREATE_USER_ROLES"),
	UPDATE_USER_ROLES("UPDATE_USER_ROLES"),
	DELETE_USER_ROLES("DELETE_USER_ROLES"),
	// USERS
	VIEW_USERS("VIEW_USERS"),	
	CREATE_USERS("CREATE_USERS"),
	UPDATE_USERS("UPDATE_USERS"),
	DELETE_USERS("DELETE_USERS");

	private final String value;
 	public String getValue() {
 		return value;
 	}
 	private FunctionalityEnum(String value) {
 		this.value = value;
 	}
}
